### PR TITLE
Add a function `asarray`

### PR DESCRIPTION
**Pull request by styra**
Add a function `asarray` which can create a shared memory copy of given array.
It's useful for who wants to share existing array to multi-processes.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Two queqstions:

1. What does
```
sa = sharedmem.asarray(a)
```
do more than 
```
sa = sharedmem.copy(numpy.asarray(a))
```

2. How similar is sharedmem.asarray comparing to numpy.asarray? It would be nice to add test cases in test_sharedmem.py to assert the examples in numpy.asarray works with sharedmem.asarray.

**Comment by styra** [comment]
Sorry, I didn't notice the function `copy`.
It seems not necessary add `asarray`.

**Comment by styra** [comment]
`sa = sharedmem.asarray(a)`  is just the same as `sa = sharedmem.copy(numpy.asarray(a))`, 
only difference is you don't convert `a` to numpy array first.

`numpy.asarray` can convert any array-like object to numpy array,
and `sharedmem.asarray` would convert array-like object to sharedmem array. 
In this sense I think the name `asarray` is suit for this function.

**Comment by rainwoodman** [comment]
It may not be worthwhile to avoid the first conversion from a list. the argument goes:

-  If numpy.asarray needs to copy, then the input object must be some really nasty thing like an list. In that case the density representation created by numpy.asarray is already much compressed than the original object, so it doesn't hurt to have a temporary copy on private memory.
- If numpy.asarray do not need to copy, then it will just create a small ndarray object containing the metadata of the array, pointint to the buffer of the input object; we will still be directly copying from that buffer anyways.

- In addition, I would prefer (for now) keeping the number of functions in sharedmem.py a minimal and avoid duplicating the entire numpy API. It's a lot of code for very little gain.

**Comment by styra** [comment]
OK, I agree. 
For the function `copy` is a better name, as it would always create a new buffer.

**Pull request closed without merging**
